### ISSUE TITLE
SchedulerAlreadyRunningError at /demo/on

### ISSUE THREAD

**Issue by mBouamama** [the-maux/tipboard#86]
i try /demo/on -> /demo/off -> /demo/on.
I got :
`Exception Type: SchedulerAlreadyRunningError`
`Exception Value: Scheduler is already running`

**Comment by the-maux** [comment]
Yes ! 
@mBouamama Thanks you for the first bug report :grinning: 
The scheduler was made for the sensors, and the route **/demo/on** is still in wip, for now it is not fully compatible with django logic.
I will fix it, i let your issue open for now

**Comment by the-maux** [comment]
Fixed in b782575 !
Thanks for the report
