### ISSUE TITLE
Data pushing format

### ISSUE THREAD

**Issue by Kuzmin-Dmitry** [the-maux/tipboard#88]
Is there way to push data in one format? 

Now I need to use string with key/value properties and json:
```
tile_id=ID&tile_template=just_value&data={"title":"Title","description":"Description","just-value":"Value"}
```

It will be more readable and easier to generate templates when using JSON:
```
{
    "data": {
        "title": "Title",
        "description": "Description",
        "just-value": "Value",
    },
    "tile_template": "just_value",
    "tile_id": "ID"
}
```

**Comment by the-maux** [comment]
One way can be with script,  like this
``` python
import requests
import json

dataToPush = {
    'tile_id': 'jv_ex'
    'tile_template': 'just_value',
    'data': json.dumps({
        'title': 'Title',
        'description': 'Description',
        'just-value': '42',
    }),
    'meta': json.dumps({
        'big_value_color': '#d50000',
        'fading_background': 'false'
    }),
}
requests.post('http://0.0.0.0:8080/api/push', data=dataToPush)
```
Data are dumped in a redis, in a JSON format, so yes you can use JSON.
Redis is also the reason why you need to serialize _**meta**_ and _**data**_ in a string format.
For all tiles, you can add the 'meta', to modify the config of the tile, or not

**Comment by Kuzmin-Dmitry** [comment]
In your case, a slightly different format is obtained. While I use this variant:
```
query_array = {
    "data": {
        "title": "Title",
        "description": "Description",
        "just-value": "Value",
    },
    "tile_template": "just_value",
    "tile_id": "ID"
}

query_string = "tile_id=" + query_array['tile_id'] + "&" + "tile_template=" + query_array['tile_template'] + "&data=" + json.dumps(query_array['data'])
```

**Comment by the-maux** [comment]
Yes, your var **query_string** is a _string_  and mine(**dataToPush**) is a _dict_, wich is not the same.  
In most webserver, to be able to use this **queryString** the webserver will need a custom parser (in your case with a '**&**' separator to fetch the data), in opposite with a dict wich is a completly native, for exemple in Tipboard(with Django) [you can do like this](https://github.com/the-maux/tipboard/blob/5227a40cad83caf182daac583072e6450074ebea/src/tipboard/app/views/api.py#L72)
The json serialisation in string, is just to simplify the dump/load from redis
