### ISSUE TITLE
Add custom tiles

### ISSUE THREAD

**Issue by Kuzmin-Dmitry** [the-maux/tipboard#93]
Hello!
How new custom tiles can be added? The option described in the old Tipboard does not work. And python scripts fill templates by html id with predefined css code

**Comment by the-maux** [comment]
Hello Dmitry !
You right, the option available in Tipboard1.0 for adding custom tiles is not working anymore.  
This features is dead in the migration to python3 & Django, this need to be fixed.
I will let your issue open until it's fixed and documented  

What do you mean with '_python scripts fill templates by html id with predefined css code_' ?
cause it's not really only html, it's a defined by a [Django template](https://docs.djangoproject.com/en/2.2/topics/templates/)

Meanwhile, if you want to try, i recommand to override the text tile (like in tipboard1.0 :stuck_out_tongue_closed_eyes: ):
- Text Django template is [here](https://github.com/the-maux/tipboard/blob/develop/src/tipboard/templates/tiles/text.html)
- Css is [here](https://github.com/the-maux/tipboard/blob/develop/src/tipboard/static/css/layout.css)
- If you need javascript, update this function with your need [here](https://github.com/the-maux/tipboard/blob/5227a40cad83caf182daac583072e6450074ebea/src/tipboard/static/tiles/text_value.js#L48)  

If you need help, don't hesitate, and you are ready to add it to the project, made a PR :grinning:

**Comment by the-maux** [comment]
Custom tile is working now, you can check the [sensors test](https://github.com/the-maux/tipboard/blob/wip/src/sensors/sensors22_custom.py)
I still need to improve it and document it

**Comment by the-maux** [comment]
Hello Dmitry,
Documentation was updated: [here](https://github.com/the-maux/tipboard/wiki/CustomTile) 
Don't hesitate to help me improve it :wink:
